source 'https://cdn.cocoapods.org'

platform :ios, '15.0'
use_frameworks!

target 'iosApp' do
  # Kotlin Multiplatform generated pod
  pod 'composeApp', :path => '../composeApp'

  # MediaPipe LLM Inference Task (used by Swift code only)
  # Using version 0.10.18 which has the correct Swift API
  pod 'MediaPipeTasksGenAI', '0.10.18'
  pod 'MediaPipeTasksGenAIC', '0.10.18'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
